apiVersion: argproj.io/v1alpha1
kind: Application
metadata:
  name: prometeus
  namespace: argo
  labels:
    app: prometeus
spec:
  project: default
  source:
    repoURL: https://gitlab.com/tomkukral/training-model.git
    targetRevision: HEAD
    path: prometeus
  destination:
    name: in-cluster
    namespace: prometeus
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
